import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/Navbar";
import Footer from "@/component/Footer";

const geistSans = Geist({
  subsets: ["latin"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html suppressHydrationWarning={false} className={`${geistSans.className}`}>
      {/* className="bg-[#FFF8E7]" */}
      <body className="bg-[#FFF8E7]">
        <header className="sticky top-0 z-50">
          <Navbar />
        </header>
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
